apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      # - image: 418272791264.dkr.ecr.ap-southeast-2.amazonaws.com/notifications:latest
      - image: asia-southeast1-docker.pkg.dev/micro-sleepr/notifications/production
        name: notifications
        env:
          - name: PORT
            value: '3000'
          - name: GOOGLE_OAUTH_CLIENT_ID
            value: 421243791534-jrujn7b0qceb1irgun3e8i7te60mpshj.apps.googleusercontent.com
          - name: GOOGLE_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google
                key: clientSecret
          - name: GOOGLE_OAUTH_REFRESH_TOKEN
            valueFrom:
              secretKeyRef:
                name: google
                key: refreshToken
          - name: SMTP_USER
            value: 100488team@gmail.com
        ports:
          - containerPort: 3000
